name: Build and Test
on: [push, pull_request]

jobs:
  build-gcc11:
    name: Build for GCC 11.2
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env: {TARGET: +build-alpine-gcc-11.2}
        run: &script |
          bash tools/earthly.sh "$TARGET"
  build-gcc10:
    name: Build for GCC 10.3
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env: {TARGET: +build-alpine-gcc-10.3}
        run: *script
