name: Build and Test
on: [push, pull_request]

jobs:
  build-gcc11:
    name: Build for GCC 11.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash tools/earthly.sh +build-alpine-gcc-11.2
  build-gcc10:
    name: Build for GCC 10.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash tools/earthly.sh +build-alpine-gcc-10.3 --cxx_flags "-fcoroutines"
