name: Build and Test
on: [push, pull_request]

jobs:
  build-gcc11:
    name: Build for GCC 11.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: /var/lib/docker/volumes/earthly-cache/
          key: gcc11
      - name: Build and Test
        run: bash tools/earthly.sh +build-alpine-gcc-11.2
  build-gcc10:
    name: Build for GCC 10.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: /var/lib/docker/volumes/earthly-cache/
          key: gcc10
      - name: Build and Test
        run: bash tools/earthly.sh +build-alpine-gcc-10.3 --cxx_flags "-fcoroutines"

  build-vs2019:
    name: Build for VS 2019
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            _build/
            ~/AppData/Local/bpt/
            !**/*.exe
          key: vs2019
      - name: Build and Test
        run: tools/build-vs2019e.bat -Toolchain tools/msvc.jsonc

  build-vs2022:
    name: Build for VS 2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            _build/
            ~/AppData/Local/bpt/
            !**/*.exe
          key: vs2022
      - name: Build and Test
        run: tools/build-vs2022e.bat -Toolchain tools/msvc.jsonc
